export const CHECKSHOW = 'CHECKSHOW';
export const SENDING_EMAIL = 'SENDING_EMAIL'
export const SEND_EMAIL_SUCCESS = 'SEND_EMAIL_SUCCESS';
export const SEND_EMAIL_FAIL = 'SEND_EMAIL_FAIL';
export const REMOVE_ALERT = 'REMOVE_ALERT';
